set(_CATKIN_CURRENT_PACKAGE "swift_setup_tf")
set(swift_setup_tf_VERSION "0.0.0")
set(swift_setup_tf_MAINTAINER "ubuntu <ubuntu@todo.todo>")
set(swift_setup_tf_PACKAGE_FORMAT "2")
set(swift_setup_tf_BUILD_DEPENDS "geometry_msgs" "roscpp" "tf")
set(swift_setup_tf_BUILD_EXPORT_DEPENDS "geometry_msgs" "roscpp" "tf")
set(swift_setup_tf_BUILDTOOL_DEPENDS "catkin")
set(swift_setup_tf_BUILDTOOL_EXPORT_DEPENDS )
set(swift_setup_tf_EXEC_DEPENDS "geometry_msgs" "roscpp" "tf")
set(swift_setup_tf_RUN_DEPENDS "geometry_msgs" "roscpp" "tf")
set(swift_setup_tf_TEST_DEPENDS )
set(swift_setup_tf_DOC_DEPENDS )
set(swift_setup_tf_URL_WEBSITE "")
set(swift_setup_tf_URL_BUGTRACKER "")
set(swift_setup_tf_URL_REPOSITORY "")
set(swift_setup_tf_DEPRECATED "")